example1:
  img: "images/urban_street_01.jpg"
  source_prompt: "360-degree panoramic image, a street with cars and buildings and trees"
  target_prompt: "360-degree panoramic image, a street with red  cars and buildings and trees"
  target_blend: "cars"
  source_blend: "street buildings"
  positive_prompt: ""
  negative_prompt: ""
  guidance_s: 1
  guidance_t: 2
  num_inference_steps: 15
  width: 1024
  height: 512
  seed: 0
  strength: 1
  cross_attention_control_schedule: 0.9
  self_attention_control_schedule: 0.9
  target_blench_thresh: 0.0
  self_blench_thresh: 0.6
  denoise: False